os: windows
language: shell
service:
  - docker

if: branch = master

script:
# - powershell set-executionpolicy unrestricted
  - docker build -t "pixpan/space-engineers" .
  - docker tag pixpan/space-engineers "pixpan/space-engineers:0.$TRAVIS_BUILD_NUMBER"
  - echo "$docker_password" | docker login -u "$docker_username" --password-stdin
  - docker push "pixpan/space-engineers"
